apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: dev
spec:
  type: ExternalName
  externalName: keycloak-headless.keycloak.svc.cluster.local
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: dev
spec:
  type: ExternalName
  externalName: loki-grafana.monitoring.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: dev
spec:
  type: ClusterIP  # Change from ExternalName to ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: argocd-server
  namespace: dev
subsets:
  - addresses:
      - ip: 10.224.0.8  # ClusterIP of argocd-server in argocd namespace
    ports:
      - port: 8080
        name: https
    

