apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-keyvault
  namespace: blue
spec:
  provider: azure
  parameters:
    clientID: eda4936d-dcfe-43e2-848d-41ccb54166de
    keyvaultName: db-secrets-k8s
    tenantId: 833c1477-5ee3-4e4b-80b4-3db55efd17fa
    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-name
          objectType: secret

  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: db-user
          key: POSTGRES_USER
        - objectName: db-password
          key: POSTGRES_PASSWORD
        - objectName: db-name
          key: POSTGRES_DB